/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mood.Analyser;

import org.junit.Test;
import org.hamcrest.CoreMatchers;
import org.junit.Assert;

public class MoodAnalyserTest {
    @Test
    public void TestMoodAnalyser1() throws Exception {
    	MoodAnalyser moodAnalyser = new MoodAnalyser();
    	
    	String mood = moodAnalyser.MoodAnalyse("This is a a happy message");
		Assert.assertThat(mood, CoreMatchers.is("HAPPY"));
    }
    @Test
    public void TestMoodAnalyser2() throws MoodAnalyserException {
    	try {
    		MoodAnalyser moodAnalyser = new MoodAnalyser();
        	
        	String mood = moodAnalyser.MoodAnalyse("");
    	}
		catch(MoodAnalyserException e) {
			Assert.assertEquals(MoodAnalyserException.ExceptionType.ENTERED_EMPTY, e.type);
		}
    }
    @Test
    public void TestMoodAnalyser3() throws MoodAnalyserException {
    	try {
    		MoodAnalyser moodAnalyser = new MoodAnalyser();
        	
        	String mood = moodAnalyser.MoodAnalyse(null);
    	}
		catch(MoodAnalyserException e) {
			Assert.assertEquals(MoodAnalyserException.ExceptionType.ENTERED_NULL, e.type);
		}
    }
}
