/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mood.Analyser;

import org.junit.Test;
import org.hamcrest.CoreMatchers;
import org.junit.Assert;

public class MoodAnalyserTest {
    @Test
    public void TestMoodAnalyser() {
    	MoodAnalyser moodAnalyser = new MoodAnalyser();
    	
    	String mood = moodAnalyser.MoodAnalyse("This is a a happy message");
		Assert.assertThat(mood, CoreMatchers.is("HAPPY"));
    }
}
