/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mood.Analyser;

public class MoodAnalyser {
    public String MoodAnalyse(String message) throws MoodAnalyserException {
    	try {
    		if(message.length() == 0) {
    			throw new MoodAnalyserException(MoodAnalyserException.ExceptionType.ENTERED_EMPTY, "Please give a proper input");
    		}
    		if(message.contains("happy")) {
        		return "HAPPY";
        	}
        	else {
        		return "SAD";
        	}
    	}
    	catch(NullPointerException e) {
    		throw new MoodAnalyserException(MoodAnalyserException.ExceptionType.ENTERED_NULL, "Please give a proper input"); 
    	}
    }
}
