/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mood.Analyser;

public class MoodAnalyser {
    public String MoodAnalyse(String message) {
    	if(message.contains("happy")) {
    		return "HAPPY";
    	}
    	else {
    		return "SAD";
    	}
    }
}
